name: Lokales
description: A new Flutter project.

dependencies:
  cupertino_icons: "^0.1.0"
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: "^0.2.0"
  flutter_redux: "^0.5.3"
  flutter_webview_plugin: "^0.3.3"
  intl: "^0.15.7"
  google_maps_flutter: "^0.5.0"
  json_annotation: "^2.1.0"
  meta: "^1.1.6"
  redux: "^3.0.0"
  redux_epics: "^0.10.4"
  redux_persist: "^0.8.2"
  redux_persist_flutter: "^0.8.1"
  rxdart: "^0.20.0"
  shared_preferences: "^0.5.1"
  transparent_image: "^1.0.0"
  uuid: "^2.0.1"
  url_launcher: "^5.0.2"

dev_dependencies:
  build_runner: ^1.1.2
  flutter_launcher_icons: "^0.6.1"
  flutter_redux_dev_tools: "^0.3.0"
  flutter_test:
    sdk: flutter
  json_serializable: "^2.0.0"
  mockito: "3.0.0"
  redux_dev_tools: "^0.4.0"
  redux_remote_devtools: "^0.0.7"

flutter_icons:
  image_path_android: "images/tlogo.png"
  image_path_ios: "images/logo.png" 
  android: true
  ios: true
  
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/chalupy.jpg
   - images/chalupy_morze.jpg
   - images/czarnocin.png
   - images/karolinow.jpg
   - images/popow.jpg
   - images/tarifa.png
   - images/tlogo.png
   - images/zaspy.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Leafy
      fonts:
        - asset: fonts/Futura-Regular.ttf
        - asset: fonts/Futura-Italic.ttf
    - family: Lokales
      fonts:
        - asset: fonts/Lokales.ttf
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
