/// Flutter icons Lokales
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Lokales
///      fonts:
///       - asset: fonts/Lokales.ttf
///
///
///
import 'package:flutter/widgets.dart';

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Lokales
///      fonts:
///       - asset: fonts/Lokales.ttf
///
///
///

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Lokales
///      fonts:
///       - asset: fonts/Lokales.ttf
///
///
///

/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Lokales
///      fonts:
///       - asset: fonts/Lokales.ttf
///
///
///

class Lokales {
  Lokales._();

  static const _kFontFam = 'Lokales';

  static const IconData logo = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData windy = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData windguru =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData deep_water =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData flat = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData shallow_water =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData waves = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData wind = const IconData(0xe80a, fontFamily: _kFontFam);
}
