update_fastlane

default_platform(:android)

lane :android_appcenter_upload do
 appcenter_upload(
    owner_name: 'lukasz.kujawiak-1',
    app_name: 'Lokales',
    apk: '../build/app/outputs/apk/app.apk',
    release_notes: sh('../../ci/release_notes.sh'),
  )
end

lane :alpha do
  upload_to_play_store(
    track: 'alpha',
    apk: '../build/app/outputs/apk/release/app-release.apk',
  )
end
