import 'Fastfile.private'

#update_fastlane

default_platform(:android)

lane :appcenter do
  lokales_appcenter_upload()
end

lane :alpha do
  upload_to_play_store(
    track: 'alpha',
    apk: '../build/app/outputs/apk/release/app-release.apk',
  )
end
